---
title: "Resources"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*Note:* I wouldn't suggest to buy books to learn R. Instead, search for resources online. R is a community and most people who use R believes in open source and free access to online resources. There are several professors who share their classes online and several blogs that explain how to perform - virtually - any task that you might need to do. Exploring these resources is key to use R and a good way to start learning!

## Learning R 

[Data Science for Public Sector](https://ds4ps.org/course_website/)
Several resources for those who are interested in a data science carrier in the public sector - including a list of cool R projects and website. They also have an online course on [data science](https://ds4ps.org/course_website/) 

[Teacups, giraffes, and statistics](https://tinystats.github.io/teacups-giraffes-and-statistics/)
An intro to undergraduate statistics in R

[Data visualization in R](https://datavizf18.classes.andrewheiss.com/) and [Statistics and data science in R](https://statsf18.classes.andrewheiss.com/)
Material from two courses entirely taught in R. The courses are master-level but there are great lectures and exercises to learn R - Dr. Andrew Heiss, GSU

[Introduction to R for undergraduate](https://web.stanford.edu/~kjytay/courses/stats32-aut2018/)

[Introduction to R, Dr. Muschelli](https://johnmuschelli.com/intro_to_r/)

## Cool R packages

[R graph gallery + codes to produce graphs](https://www.r-graph-gallery.com/)
Provide codes to build several graphs in R. 

[Create interactive dashboards in R with Shiny](https://shiny.rstudio.com/gallery/)

[Interactive graphs in R with Plot.ly](https://plot.ly/r/)

[Explore cool packages in R](https://awesome-r.com/)
This might require some pre-knowledge on how R works.

## Exploring R

[A list of additional resources for learning R](https://csgillespie.wordpress.com/2011/01/28/r-programming-books-updated/)

[Makeover Mondays](https://www.makeovermonday.co.uk/)
A community that builds graphs to explore public data every Monday. Graphs are available online. 

```{css, echo=F}

.powered-by-datacamp {
  display: none !important;
}

.datacamp-exercise {
  margin: 0 0 1em 0 !important;
}

p {
color: black;
margin: 0 0 20px 0;
}

p.caption {
    text-align: center;
    font-style: italic;
}

td {
    padding: 3px 10px 3px 10px;
    }

table
{ 
    margin-left: auto;
    margin-right: auto;
    margin-top:80px;
    margin-bottom:100px;
}

h1, h2{
  margin-top:100px;
  margin-bottom:20px;
}

H5{
    text-align: center;
    color: gray;
    font-size:0.8em;
}

img {
    max-width: 90%;
    display: block;
    margin-right: auto;
    margin-left: auto;
    margin-top:30px;
    margin-bottom:20px;
}

pre {
  overflow-x: auto;
}

pre code {
   display: block; 
   padding: 0.5em;
   margin-bottom:20px;
}

code {
  font-size: 92%;
  border: 10px solid #F8F8F8;
  margin-bottom: 2px;
}

code[class] {
  background-color: #F8F8F8;
}

```